using System.Net;
using System.Linq;
using System.Text.RegularExpressions;
using DiaconateSchool.Application.DTOs;
using DiaconateSchool.Application.Interfaces;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;

namespace DiaconateSchool.Infrastructure.Services;

/// <summary>
/// Fetches today's Coptic Synaxarium (occasion + saints' commemorations, in
/// Arabic, with the full story text) from st-takla.org and caches it until
/// the next Cairo midnight, since the content is the same all day.
///
/// The source page (https://st-takla.org/zJ/index.php/ar-synaxarium) has no
/// public JSON API, so this scrapes it — but the markup is generated by the
/// same Joomla template every day with fixed inline `style="..."` attributes
/// per role (day heading vs. saint title vs. story paragraph), which makes it
/// reliably parseable without a full HTML parser: each &lt;p&gt; is classified
/// by which distinctive style rule it carries. If the page layout ever
/// changes, GetTodayAsync degrades to the last cached day rather than
/// throwing, so a broken scrape never takes the landing page down with it.
/// </summary>
public class SynaxariumService : ISynaxariumService
{
    private const string SourceUrl = "https://st-takla.org/zJ/index.php/ar-synaxarium";
    private const string ImageSourceUrl = "https://bubastis.deltamultisys.com/Synaxarium/Index";
    private const string ImageSourceOrigin = "https://bubastis.deltamultisys.com";
    private const string CacheKeyPrefix = "synaxarium:";

    // Anchors bounding the actual day content within the page — everything
    // between the last divider before the blessing paragraph and the "back to
    // top" arrow that follows the last saint entry.
    private const string StartAnchor = "height:3px;\"><hr/></div><br /></div>";
    private const string EndAnchor = "&uarr;";

    private static readonly Regex ParagraphRegex = new(
        "<p\\b[^>]*?style=\"([^\"]*)\"[^>]*>(.*?)</p>",
        RegexOptions.Singleline | RegexOptions.Compiled);
    private static readonly Regex TagRegex = new("<[^>]+>", RegexOptions.Compiled);

    private readonly IHttpClientFactory _httpClientFactory;
    private readonly IMemoryCache _cache;
    private readonly ILogger<SynaxariumService> _logger;

    public SynaxariumService(IHttpClientFactory httpClientFactory, IMemoryCache cache, ILogger<SynaxariumService> logger)
    {
        _httpClientFactory = httpClientFactory;
        _cache = cache;
        _logger = logger;
    }

    public async Task<SynaxariumDayDto?> GetTodayAsync()
    {
        var cairoNow = GetCairoNow();
        var cacheKey = CacheKeyPrefix + cairoNow.ToString("yyyy-MM-dd");

        if (_cache.TryGetValue<SynaxariumDayDto>(cacheKey, out var cached) && cached != null)
            return cached;

        try
        {
            var day = await FetchAndParseAsync();
            if (day == null || day.Saints.Count == 0)
                return FallbackToLastKnown(cacheKey);

            var midnightCairo = cairoNow.Date.AddDays(1);
            var ttl = midnightCairo - cairoNow;
            _cache.Set(cacheKey, day, ttl);
            // Keep as the "last known good" independent of the daily key, so a
            // scrape failure tomorrow still has something to fall back to.
            _cache.Set(CacheKeyPrefix + "last-known-good", day, TimeSpan.FromDays(7));
            return day;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Synaxarium fetch failed; falling back to last known day.");
            return FallbackToLastKnown(cacheKey);
        }
    }

    private SynaxariumDayDto? FallbackToLastKnown(string todayCacheKey)
    {
        if (_cache.TryGetValue<SynaxariumDayDto>(CacheKeyPrefix + "last-known-good", out var lastGood) && lastGood != null)
        {
            var stale = new SynaxariumDayDto
            {
                DayHeading = lastGood.DayHeading,
                Blessing = lastGood.Blessing,
                Saints = lastGood.Saints,
                IsStale = true,
            };
            // Cache briefly so repeated hits during an outage don't all hit the network.
            _cache.Set(todayCacheKey, stale, TimeSpan.FromMinutes(15));
            return stale;
        }
        return null;
    }

    private async Task<SynaxariumDayDto?> FetchAndParseAsync()
    {
        var client = _httpClientFactory.CreateClient(nameof(SynaxariumService));
        client.Timeout = TimeSpan.FromSeconds(12);
        using var request = new HttpRequestMessage(HttpMethod.Get, SourceUrl);
        // Without a browser-like UA the site occasionally serves a stripped page.
        request.Headers.UserAgent.ParseAdd("Mozilla/5.0 (compatible; DiaconateSchoolBot/1.0)");

        using var response = await client.SendAsync(request);
        response.EnsureSuccessStatusCode();
        var html = await response.Content.ReadAsStringAsync();

        var startIdx = html.IndexOf(StartAnchor, StringComparison.Ordinal);
        var endIdx = html.IndexOf(EndAnchor, StringComparison.Ordinal);
        if (startIdx < 0 || endIdx < 0 || endIdx <= startIdx) return null;

        var slice = html.Substring(startIdx + StartAnchor.Length, endIdx - (startIdx + StartAnchor.Length));

        string? blessing = null;
        string? heading = null;
        var saints = new List<SynaxariumEntryDto>();
        SynaxariumEntryDto? current = null;

        foreach (Match m in ParagraphRegex.Matches(slice))
        {
            var style = m.Groups[1].Value;
            var text = StripTags(m.Groups[2].Value);
            if (string.IsNullOrWhiteSpace(text)) continue;

            var isDarkRed = style.Contains("color:#8b0000", StringComparison.OrdinalIgnoreCase);

            if (isDarkRed && style.Contains("font-size:18px", StringComparison.OrdinalIgnoreCase))
            {
                blessing = text;
            }
            else if (!isDarkRed && style.Contains("font-size:20px", StringComparison.OrdinalIgnoreCase)
                     && style.Contains("text-align:center", StringComparison.OrdinalIgnoreCase))
            {
                heading = text;
            }
            else if (isDarkRed && style.Contains("font-size:24px", StringComparison.OrdinalIgnoreCase))
            {
                if (current != null) saints.Add(current);
                current = new SynaxariumEntryDto { Title = text };
            }
            else if (!isDarkRed && style.Contains("font-size:20px", StringComparison.OrdinalIgnoreCase)
                     && style.Contains("text-align:justify", StringComparison.OrdinalIgnoreCase))
            {
                if (current != null)
                    current.Story = string.IsNullOrEmpty(current.Story) ? text : current.Story + " " + text;
            }
        }
        if (current != null) saints.Add(current);

        if (heading == null || saints.Count == 0) return null;

        // Best-effort — a second source (bubastis) carries a real icon photo
        // per saint that st-takla's page doesn't have. Never lets an image
        // fetch failure take down the (already-complete) text result.
        try
        {
            await AttachImagesAsync(saints);
        }
        catch (Exception ex)
        {
            _logger.LogInformation(ex, "Synaxarium image fetch failed; continuing without icons.");
        }

        return new SynaxariumDayDto
        {
            DayHeading = heading,
            Blessing = BuildBlessing(heading) ?? blessing ?? string.Empty,
            Saints = saints,
        };
    }

    private static readonly Regex SaintCardMarker = new("class=\"saint-card\"", RegexOptions.Compiled);
    private static readonly Regex SaintImageRegex = new("<img\\s+src=\"([^\"]*)\"", RegexOptions.Compiled);
    private static readonly Regex SaintTitleRegex = new("<h3>(.*?)</h3>", RegexOptions.Singleline | RegexOptions.Compiled);
    // The site's evergreen "major feasts" reminder appears as its own card
    // every day — it isn't a specific saint, so it's never a useful image match.
    private const string GenericFeastMarker = "الأعياد السيدية";

    // Fuzzy title match (word-overlap) rather than positional, since the two
    // sites don't list saints in the same order and bubastis's card list also
    // includes that generic entry st-takla doesn't have.
    private async Task AttachImagesAsync(List<SynaxariumEntryDto> saints)
    {
        var client = _httpClientFactory.CreateClient(nameof(SynaxariumService));
        client.Timeout = TimeSpan.FromSeconds(8);
        using var request = new HttpRequestMessage(HttpMethod.Get, ImageSourceUrl);
        request.Headers.UserAgent.ParseAdd("Mozilla/5.0 (compatible; DiaconateSchoolBot/1.0)");

        using var response = await client.SendAsync(request);
        if (!response.IsSuccessStatusCode) return;
        var html = await response.Content.ReadAsStringAsync();

        var cardStarts = SaintCardMarker.Matches(html).Select(m => m.Index).ToList();
        if (cardStarts.Count == 0) return;
        cardStarts.Add(html.Length);

        var candidates = new List<(string Title, string ImageUrl, HashSet<string> Words)>();
        for (var i = 0; i < cardStarts.Count - 1; i++)
        {
            var card = html.Substring(cardStarts[i], cardStarts[i + 1] - cardStarts[i]);
            var titleMatch = SaintTitleRegex.Match(card);
            var imageMatch = SaintImageRegex.Match(card);
            if (!titleMatch.Success || !imageMatch.Success) continue;

            var title = StripTags(titleMatch.Groups[1].Value);
            if (string.IsNullOrWhiteSpace(title) || title.Contains(GenericFeastMarker, StringComparison.Ordinal)) continue;

            var imageUrl = imageMatch.Groups[1].Value;
            if (!imageUrl.StartsWith("http", StringComparison.OrdinalIgnoreCase))
                imageUrl = ImageSourceOrigin + imageUrl;

            candidates.Add((title, imageUrl, TitleWords(title)));
        }

        foreach (var saint in saints)
        {
            var saintWords = TitleWords(saint.Title);
            var best = candidates
                .Select(c => (c, overlap: c.Words.Intersect(saintWords).Count()))
                .Where(x => x.overlap > 0)
                .OrderByDescending(x => x.overlap)
                .FirstOrDefault();

            if (best.c.ImageUrl != null)
            {
                saint.ImageUrl = best.c.ImageUrl;
                candidates.Remove(best.c); // don't match two saints to the same photo
            }
        }
    }

    // Boilerplate that appears in nearly every entry's title ("تذكار",
    // "القديس"...) — without excluding these, two unrelated saints "match" on
    // a shared generic word (that's the bug this stoplist fixes: ورشنوفيوس
    // and أندراوس both contain "القديس", which isn't a real match).
    private static readonly HashSet<string> TitleStopWords = new()
    {
        "تذكار", "استشهاد", "نياحة", "رسامة", "نقل", "اعضاء", "دخول", "خروج",
        "القديس", "القديسة", "القديسين", "الشهيد", "الشهيدة", "الرسول", "الانبا",
        "البابا", "الاسقف", "مار", "الاب", "هذا", "اليوم", "من", "في", "الى",
    };

    // Words of 3+ chars, minus the stoplist above — short Arabic connectors
    // and role-boilerplate would otherwise "match" almost anything and defeat
    // the point of comparing. Alef variants are normalized first — the two
    // sites spell the same name differently (اندراوس vs. أندراوس), which
    // would otherwise silently defeat an exact-word match.
    private static HashSet<string> TitleWords(string title)
        => NormalizeAlef(title).Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Where(w => w.Length >= 3 && !TitleStopWords.Contains(w))
            .ToHashSet();

    private static string NormalizeAlef(string s)
        => s.Replace('أ', 'ا').Replace('إ', 'ا').Replace('آ', 'ا');

    private static string StripTags(string html)
        => WebUtility.HtmlDecode(TagRegex.Replace(html, string.Empty)).Trim();

    // The traditional opening greeting, in the exact fixed wording — not the
    // scraped page's own phrasing, which varies. The one part that legitimately
    // changes day to day is استقباله vs. إنقضاءه: the first half of a Coptic
    // month (1–15) is "welcomed" (استقباله), the second half (16–30) is
    // "concluded" (إنقضاءه). Day/month are read off the already-parsed day
    // heading (e.g. "29- اليوم التاسع والعشرين - شهر أبيب") rather than
    // scraped separately, so this never disagrees with the heading shown
    // right below it.
    private static readonly Regex DayHeadingRegex = new(@"^(\d+)-.*?شهر\s+(.+)$", RegexOptions.Compiled);

    private static string? BuildBlessing(string dayHeading)
    {
        var m = DayHeadingRegex.Match(dayHeading.Trim());
        if (!m.Success || !int.TryParse(m.Groups[1].Value, out var day)) return null;
        var month = m.Groups[2].Value.Trim();
        var phase = day is >= 1 and <= 15 ? "استقباله" : "إنقضاءه";

        return "بسم الآب والإبن والروح القدس الإله الواحد آمين. "
             + $"اليوم {day} من شهر {month} أحسن الله {phase} وأعاده علينا وعليكم "
             + "ونحن متمتعين بهدوء وإطمئنان مغفوري اخطايا والزلات من قبل مراحم الرب يا آبائي وإخوتي آمين.";
    }

    private static DateTime GetCairoNow()
    {
        try
        {
            var cairoZone = TimeZoneInfo.FindSystemTimeZoneById(
                OperatingSystem.IsWindows() ? "Egypt Standard Time" : "Africa/Cairo");
            return TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, cairoZone);
        }
        catch (TimeZoneNotFoundException)
        {
            return DateTime.UtcNow.AddHours(2); // Cairo is UTC+2 (no DST since 2016)
        }
    }
}
